language: python
python: 2.7
sudo: false
os: linux
dist: xenial

# the search tests are currently broken by a failing xapian import
script: ./pytest MoinMoin/ --ignore MoinMoin/support/ --ignore MoinMoin/search/_tests/test_search.py
